-- ============================================================
-- RLS POLICIES FOR user_sessions TABLE
-- Allows anon key access (custom auth, not Supabase Auth)
-- ============================================================

-- Enable RLS (should already be enabled by default)
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

-- Allow SELECT (validate sessions, get active sessions)
CREATE POLICY "Allow public read on user_sessions"
  ON user_sessions
  FOR SELECT
  TO anon
  USING (true);

-- Allow INSERT (create new sessions on login)
CREATE POLICY "Allow public insert on user_sessions"
  ON user_sessions
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Allow UPDATE (deactivate sessions, touch last_activity, extend expiry)
CREATE POLICY "Allow public update on user_sessions"
  ON user_sessions
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

-- Allow DELETE (cleanup expired sessions if needed)
CREATE POLICY "Allow public delete on user_sessions"
  ON user_sessions
  FOR DELETE
  TO anon
  USING (true);
